In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import gmaps.datasets

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("WeatherPy_vacation.csv")
vacation_df.head()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,3,Hasaki,JP,91.29,overcast clouds,35.7333,140.8333,Kamisu
1,13,Rikitea,PF,74.52,overcast clouds,-23.1203,-134.9692,Rikitea
2,15,Victoria,HK,92.03,overcast clouds,22.2855,114.1577,Hong Kong
3,17,Bethel,US,74.77,overcast clouds,41.3712,-73.4140,Danbury
4,18,Touros,BR,74.30,few clouds,-5.1989,-35.4608,Touros

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [4]:
# 4a. Add a marker layer for each city to the map.
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [5]:
# Creating new DF for US Vacations
us_vacation_df = vacation_df.loc[(vacation_df['Country'] == 'US')]
us_vacation_df.head(10)

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,17,Bethel,US,74.77,overcast clouds,41.3712,-73.4140,Danbury
5,19,Kapaa,US,82.72,light rain,22.0752,-159.3190,Kapaʻa
8,23,Kahului,US,81.66,scattered clouds,20.8947,-156.4700,Kahului
11,32,Brewster,US,75.00,overcast clouds,41.3973,-73.6171,Carmel Hamlet
23,55,Westport,US,78.98,scattered clouds,41.1415,-73.3579,Norwalk
39,89,Fortuna,US,74.48,scattered clouds,40.5982,-124.1573,Fortuna
49,103,Hilo,US,80.33,moderate rain,19.7297,-155.0900,Hilo
59,133,San Patricio,US,84.83,few clouds,28.0170,-97.5169,Sinton
79,171,Saint George,US,91.63,clear sky,37.1041,-113.5841,St. George
82,180,West Wendover,US,87.01,clear sky,40.7391,-114.0733,Wendover

In [6]:
# Reorder columns for pref
new_column_order = ['City_ID', 'City', 'Country', 'Lat', 'Lng', 'Max Temp', 'Current Description']
us_vacation_df = us_vacation_df[new_column_order]
us_vacation_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Current Description
3,17,Bethel,US,41.3712,-73.4140,74.77,overcast clouds
5,19,Kapaa,US,22.0752,-159.3190,82.72,light rain
8,23,Kahului,US,20.8947,-156.4700,81.66,scattered clouds
11,32,Brewster,US,41.3973,-73.6171,75.00,overcast clouds
23,55,Westport,US,41.1415,-73.3579,78.98,scattered clouds
39,89,Fortuna,US,40.5982,-124.1573,74.48,scattered clouds
49,103,Hilo,US,19.7297,-155.0900,80.33,moderate rain
59,133,San Patricio,US,28.0170,-97.5169,84.83,few clouds
79,171,Saint George,US,37.1041,-113.5841,91.63,clear sky
82,180,West Wendover,US,40.7391,-114.0733,87.01,clear sky

In [7]:
# Picking Random cities from US list above
start = float(input("What is your Starting City_ID from US List you would like for your trip? "))
stop1 = float(input("What is your First Stop City_ID from US List you would like for your trip? "))
stop2 = float(input("What is your Second Stop City_ID from US List you would like for your trip? "))
stop3 = float(input("What is your Thirth Stop City_ID from US List you would like for your trip? "))
end = float(input("What is your Last City_ID from US List you would like for your trip? "))

What is your Starting City_ID from US List you would like for your trip? 17
What is your First Stop City_ID from US List you would like for your trip? 32
What is your Second Stop City_ID from US List you would like for your trip? 55
What is your Thirth Stop City_ID from US List you would like for your trip? 89
What is your Last City_ID from US List you would like for your trip? 17

In [9]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = us_vacation_df.loc[(us_vacation_df['City_ID'] == start)]
vacation_start = vacation_start.iloc[0]

vacation_stop1 = us_vacation_df.loc[(us_vacation_df['City_ID'] == stop1)]
vacation_stop1 = vacation_stop1.iloc[0]

vacation_stop2 = us_vacation_df.loc[(us_vacation_df['City_ID'] == stop2)] 
vacation_stop2 = vacation_stop2.iloc[0]
                                    
vacation_stop3 = us_vacation_df.loc[(us_vacation_df['City_ID'] == stop3)]
vacation_stop3 = vacation_stop3.iloc[0]

vacation_end = us_vacation_df.loc[(us_vacation_df['City_ID'] == end)]
vacation_end = vacation_end.iloc[0]


print("Your Starting Destination is " + vacation_start["City"] + ", " + vacation_start["Country"])
print("Your First Stop is " + vacation_stop1["City"] + ", " + vacation_stop1["Country"])
print("Your Second Stop is " + vacation_stop2["City"] + ", " + vacation_stop2["Country"])                                     
print("Your Thirth Stop is " + vacation_stop3["City"] + ", " + vacation_stop3["Country"])                                     
print("Your Last Stop in your vacation is " + vacation_end["City"] + ", " + vacation_end["Country"])

Your Starting Destination is Bethel, US
Your First Stop is Brewster, US
Your Second Stop is Westport, US
Your Thirth Stop is Fortuna, US
Your Last Stop in your vacation is Bethel, US

In [10]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start[["Lat", "Lng"]]
print(start)

Lat    41.3712
Lng    -73.414
Name: 3, dtype: object

In [11]:
stop1 = vacation_stop1[["Lat", "Lng"]]
print(stop1)

Lat    41.3973
Lng   -73.6171
Name: 11, dtype: object

In [12]:
stop2 = vacation_stop2[["Lat", "Lng"]]
print(stop2)

Lat    41.1415
Lng   -73.3579
Name: 23, dtype: object

In [13]:
stop3 = vacation_stop3[["Lat", "Lng"]]
print(stop3)

Lat     40.5982
Lng   -124.1573
Name: 39, dtype: object

In [14]:
end = vacation_end[["Lat", "Lng"]]
print(end)

Lat    41.3712
Lng    -73.414
Name: 3, dtype: object

In [ ]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

start = (41.3712, -73.414)
stop1 = (41.3973, -73.6171)
stop2 = (41.1415, -73.3579)
stop3 = (40.5982, -124.1573)
end = (41.3712, -73.414)

fig = gmaps.figure()
sart2end_via_stops = gmaps.directions_layer(
        start, end, waypoints=[stop1, stop2, stop3],
        travel_mode='DRIVING')
fig.add_layer(sart2end_via_stops)
fig

In [17]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
us_vacation_df = pd.concat([us_vacation_df],ignore_index=True)
us_vacation_df

,City_ID,City,Country,Lat,Lng,Max Temp,Current Description
0,17,Bethel,US,41.3712,-73.4140,74.77,overcast clouds
1,19,Kapaa,US,22.0752,-159.3190,82.72,light rain
2,23,Kahului,US,20.8947,-156.4700,81.66,scattered clouds
3,32,Brewster,US,41.3973,-73.6171,75.00,overcast clouds
4,55,Westport,US,41.1415,-73.3579,78.98,scattered clouds
5,89,Fortuna,US,40.5982,-124.1573,74.48,scattered clouds
6,103,Hilo,US,19.7297,-155.0900,80.33,moderate rain
7,133,San Patricio,US,28.0170,-97.5169,84.83,few clouds
8,171,Saint George,US,37.1041,-113.5841,91.63,clear sky
9,180,West Wendover,US,40.7391,-114.0733,87.01,clear sky
10,186,Brainerd,US,46.3580,-94.2008,79.05,clear sky
11,197,Portland,US,45.5234,-122.6762,84.20,scattered clouds
12,216,East Hemet,US,33.7400,-116.9389,93.52,scattered clouds
13,225,Asheville,US,35.6009,-82.5540,73.17,few clouds
14,241,Beatrice,US,40.2681,-96.7470,84.00,clear sky
15,255,Half Moon Bay,US,37.4636,-122.4286,77.63,few clouds
16,271,Russell,US,32.3502,-85.1999,76.23,scattered clouds
17,307,Destin,US,30.3935,-86.4958,82.02,broken clouds
18,309,Meadow Lake,US,34.8014,-106.5436,73.11,overcast clouds
19,346,Ahuimanu,US,21.4447,-157.8378,87.51,light rain
20,355,Nanakuli,US,21.3906,-158.1547,87.75,scattered clouds
21,364,Key West,US,24.5557,-81.7826,87.80,clear sky
22,377,Guthrie,US,35.8789,-97.4253,86.67,clear sky
23,379,Havelock,US,34.8791,-76.9013,82.94,broken clouds
24,381,Fort Morgan,US,40.2503,-103.8000,81.82,clear sky
25,400,East Stroudsburg,US,40.9995,-75.1813,72.84,overcast clouds
26,404,Avera,US,33.1940,-82.5271,82.27,light rain
27,444,Price,US,39.5994,-110.8107,78.06,clear sky
28,449,Niceville,US,30.5169,-86.4822,81.95,overcast clouds
29,455,Old Saybrook,US,41.2918,-72.3762,74.39,scattered clouds
30,466,Sterling,US,39.0062,-77.4286,79.16,clear sky
31,468,Avenal,US,36.0041,-120.1290,94.82,clear sky
32,472,Staunton,US,38.1496,-79.0717,76.68,overcast clouds
33,495,Salinas,US,36.6777,-121.6555,75.42,clear sky
34,509,Pacific Grove,US,36.6177,-121.9166,71.15,scattered clouds
35,515,Mandan,US,46.8267,-100.8896,83.41,scattered clouds
36,521,Labelle,US,26.7617,-81.4384,82.98,overcast clouds
37,546,San Ramon,US,37.7799,-121.9780,85.66,clear sky
38,557,Santa Ana,US,33.7456,-117.8678,87.98,few clouds
39,567,Ukiah,US,39.1502,-123.2078,87.69,clear sky
40,574,Makakilo City,US,21.3469,-158.0858,86.32,scattered clouds
41,588,Laguna,US,38.4210,-121.4238,91.24,clear sky
42,599,Shasta Lake,US,40.6804,-122.3708,77.74,overcast clouds
43,631,Riverton,US,40.5219,-111.9391,87.04,clear sky
44,638,Wilmington,US,34.2257,-77.9447,82.31,clear sky
45,661,Pierre,US,44.3683,-100.3510,92.86,clear sky
46,664,Fairhope,US,30.5230,-87.9033,83.95,broken clouds
47,680,Galveston,US,29.3669,-94.9669,84.96,scattered clouds
48,711,Rexburg,US,43.8260,-111.7897,83.71,clear sky

In [18]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
mark_info = [info_box_template.format(**row) for index, row in us_vacation_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = us_vacation_df[["Lat", "Lng"]]

In [19]:
# 11a. Add a marker layer for each city to the map.
city_mark = us_vacation_df["City"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=mark_info)

fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))